### ISSUE TITLE
download_KEGGfile function not working

### ISSUE THREAD

**Issue by janstrauss1** [slzhao/KEGGprofile#3]
Hello there,

I noticed that the `download_KEGGfile` function is currently not working.
When I am trying to run `download_KEGGfile(pathway_id="00010", species="eco", target_dir = getwd())`, only the `image/png` files and an empty 1 byte XML map file get downloaded to my working directory.

```
[1] "Downloading files: 1/1"
trying URL 'http://www.genome.jp/kegg/pathway/eco/eco00010.png'
Content type 'image/png' length 28195 bytes (27 KB)
==================================================
downloaded 27 KB

trying URL 'http://www.genome.jp/kegg/pathway/map/map00010.png'
Content type 'image/png' length 26739 bytes (26 KB)
==================================================
downloaded 26 KB 
```

I guess the problem might relate to some recent changes in the KEGG API, but I wonder if there might be a fix to my `download_KEGGfile` problem?

For now I'm manually downloading specific KEGG maps from [https://www.kegg.jp/kegg/pathway.html](https://www.kegg.jp/kegg/pathway.html) to visualize expression profiles on KEGG maps.

Many thanks in advance for your help,

Jan

**Comment by slzhao** [comment]
Hello Jan,

This should be fixed in last month. Please let me know if you still have
the issue.

Best,
Shilin

**Comment by NiclasFester** [comment]
Hello @slzhao,
i tried to use this function recently and stumbled across the same problem as @janstrauss1. Did you find a work-around for the problem or is it not fixed yet?

As with Jan, the download of the *.png files is working flawlessly, but the *.xml files are empty.
Strangely the analysis is working, so i get a list of significantly enriched pathways, but the plots can't be calculated due to empty *.xml files.

Thank you in advance and greetings,
Niclas
